apiVersion: v1
kind: Pod
metadata:
  name: nginxwebserver
spec:
  containers:
    - image: nginx
      name: container1
    - image: busybox
      name: container2
      # command:                  Simliar to ENTRYPOINT in docker
      #   - sleep
      #   - "3600"

      # command: ["sleep","3000"]

      # command: ["sleep"]
      # args: ["3000"]

      args: ["sleep","3000"]      # Similar to CMD in docker