# terraform {
#   required_version = ">= 0.12"
#   required_providers {
#     docker = {
#         source = "kreuzwerker/docker"
#         version = ">=2.13.0"
#     }
#   }

# }

# Provider - local

resource "local_file" "pet" {
  filename        = ".files/pets.txt"
  content         = "we love"
  file_permission = "0777"
}

resource "local_sensitive_file" "foo" {
  filename        = "${path.module}/.files/foo.txt"
  content         = "this is sensitive"
  file_permission = "0777"
}

# provider - Random

resource "random_pet" "my-pet" {
  length    = "3"
  separator = "."
  prefix    = "Mr"
}

#Making code reusble by use of variables

resource "local_file" "newpet" {
  filename = var.filename
  content  = var.content
}

resource "random_pet" "my-newpet" {
  prefix    = var.prefix
  separator = var.separator
  length    = var.length
}

# use of other data types like list, map, set, object

resource "local_file" "mynewfile" {
  filename = ".files/mynewfile.txt"
  content  = var.file-content["statement1"]
}

resource "random_pet" "mynewpet" {
  prefix = var.prefix-list[0]

}

# Since in real senerio there is always dependency bw two resources lets use random pet id generated as content by reference expression for local file

resource "local_file" "petfile" {
  filename = ".files/mypetfile.txt"
  content  = "Thia ia my ${random_pet.mynewpet.id}" #syntex - <provider_resource type>.logicalname.id
}

# terraform is intellignet enough to understad the source of dependeny to be created first and deleted at last
# but we can still make sure this by DEPENDS_ON ARGUMENT

resource "local_file" "bestpets" {
  filename = ".files/${random_pet.mynewpet.id}.txt"
  content  = "append ${local_file.petfile.content}"

  depends_on = [
    random_pet.mynewpet,
    local_file.petfile
  ]
}


#OUTPUT VARIABLE
# we saw input variable above, since we know random_pet is generating an id we can store this in a output variable, inside this for value we use the reference expression

# syntex
# output <variable_name>{
#     value = <variable_value>
#     <arguments>
# }

output "my-pet" {
  value       = random_pet.mynewpet.id
  description = "Records the value of pet id generated by random_pet resource"
}

# output variable get printed - terraform output / terraform output <variable>


# LIFECYCLE RULES

#create_before_destroy

resource "local_file" "test" {
    filename = ".files/test.txt"
    content = "demo"

    lifecycle {
        create_before_destroy = true
    }
}

# prevent_destroy

resource "local_file" "test2" {
    filename = ".files/test2.txt"
    content = "demo"  # any changes in this resource is prevented

    lifecycle {
        prevent_destroy = false
    }
}

# Since this argument must be present in configuration for the protection to apply, 
# note that this setting does not prevent the remote object from being destroyed 
# if the resource block were removed from configuration entirely: in that case, 
# the prevent_destroy setting is removed along with it, and so Terraform will allow the destroy operation to succeed.

# ignore_changes

 # In some rare cases, settings of a remote object are modified by processes outside of Terraform, 
 # which Terraform would then attempt to "fix" on the next run.

#  for example - the changes made to tags of a server outside terraform are ignored, when we put tags in ignore_changes list of argumet


# DATA SOURCES
# Data sources allow Terraform to use information defined outside of Terraform,

data "local_file" "dog" {
    filename = "./dogs.txt"
}

# A data block requests that Terraform read from a given data source ("local_file") 
# and export the result under the given local name ("dog"). 
# The name is used to refer to this resource from elsewhere in the same Terraform module, 
# but has no significance outside of the scope of a module.

# we can simply use this data by reference expression

resource "local_file" "newtxt" {
    filename = ".files/newtxt.txt"
    content = data.local_file.dog.content
}

# COUNT

resource "local_file" "newnew" {
    filename = var.filenamelist[count.index] # or filename = element(var.filenamelist,count.index)
    count = length(var.filenamelist)
    content = "ssa"
}

# the count creates resource as a list while for each creates as a map

# FOR EACH
# for each only support SET and MAP

resource "local_file" "neweach" {
    filename = each.value

    for_each = toset(var.filenamelist)

    content = "anthing"
    
}

#*********************************************** USING MODULES
/*
resource "azurerm_resource_group" "myRG" {
  name     = "example-resources"
  location = "West Europe"
}

module "any-name-webserver"{
  source = ".modules/webserver-module"          # this will all .tf files in that module

#  provider                                   # we can also specify another provider for module, this will ovveride the one we are using in root modlue

  vnet_name = "webApplication"
  vnet_address_space = ["10.0.0.0/16"]
  rg_location = "East US"
  rg_name = azurerm_resource_group.myRG.name
  sub_address_space = ["10.0.2.0/24"]
  vm_name = "Webserver123"
}

# If we want to have some output from this module we can have it by output variable in module

# For example, if a virtual machine requires software installation, antivirus protection, 
# or the ability to run a script inside it, you can use a VM extension.

resource "azurerm_virtual_machine_extension" "example" {
  name                 = "hostname"
  virtual_machine_id   =  module.any-name-webserver.webserver-details.id
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"

  settings = <<SETTINGS
    {
        "commandToExecute": "hostname && uptime"
    }
SETTINGS


  tags = {
    environment = "Production"
  }
}


# Thats how modules are useful, we can also create modules inside of modules
#  but terraform suggests to have only root (this file) and child modules (the one which we called in source)

*/