version: '3'          #this is by default/needs to be there for version of docker compose
services:             # this contains list of our containers, and each container has its config inside it

  my-app: 
    image: 323445232354523.dkr.ecr.eu-central-1.amazonaws.com/my-app:1.0  #to pull this image the enviorment from where we run docker compose should be loogin in to aws/private registry already
    port:
    - 3000:3000
  mongodb:
    image: mongo    #by default docker looks for image in docker hub so we dont need to specify like docker.io/library/mongo
    ports:
    - 27017:27017
    enviornment:
    - MONGO_INITDB_USERNAME= admin
    - MONGO_INITDB_ROOT_PASSWORD = password
    volumes:
    - db-data: /var/lib/mysql/data
  mongo-express:
    image: mongo-express
    ports:
    - 8080:8081
    enviornment:
    - ME_CONFIG_MONGODB_ADMINUSERNAME = admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD = password
    - ME_CONFIG_MONGODB_SERVER  = mongodb

volumes:
  db-data
  